---

- name: Update grub
  ansible.builtin.shell: >
    update-grub
  when: not ansible_check_mode

- name: Restart service
  ansible.builtin.systemd:
    name: "{{ apparmor_service_name }}"
    state: restarted
  when: not ansible_check_mode
