---

- name: Update grub
  ansible.builtin.shell: >
    update-grub
  when: not ansible_check_mode

- name: Restart service
  ansible.builtin.command:
    cmd: /lib/apparmor/apparmor.systemd reload
  when: not ansible_check_mode

